name: Deploy Doc To TengCloud

# trigger condition
on:
  push: 
    branches:
      - main
      
# jobs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          rsist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
        
      - name: Build
        run: yarn install && yarn run build

      - name: Install CloudBase CLI
        run: yarn global add @cloudbase/cli

      - name: Login To CloudBase
        run: tcb login --apiKeyId ${{secrets.SECRET_ID}} --apiKey ${{secrets.APP_ID}}
 
      - name: Deploy
        run: cd build && tcb hosting deploy -e uniplore-ds-docs-9fogovk55a3aa71
      
    
